#!/bin/bash
#
# Usage: timesup TIME|now
#
#  TIME  start at the given schedule format HH:MM
#
# Behavior:
#
# at the given time, it countdowns some alerts
# when the countdown is over it display a visible anoying message
# after a lock_delay it locks the screen
#
# if the argument is 'now' it starts the countdown immediately

countdown=20
lock_delay=20
icon=dialog-information
#icon=dialog-error

msg="Il reste %d secondes"
end_msg="FIN"
nb_stop=4


# check args
if [[ $# -ne 1 ]] 
then
    echo "error: timesup TIME"
    exit 1
fi
at_time=$1

skip_at=0
if [[ "$at_time" == "now" ]]
then
    skip_at=1
fi

regexp='^[0-9]{2}:[0-9]{2}$'
if [[ $skip_at -eq 0 ]] && [[ ! "$at_time" =~ $regexp ]]
then
    echo "error: format for TIME: now or HH:MM"
    exit 1
fi

# schedule delayed alarm
if [[ $skip_at -eq 0 ]]
then
    echo "$(readlink -f $0) now" | at $at_time
    exit 0
fi

# NOW !

# countdown loop
for s in $(seq $countdown -1 1)
do
    txt=$(printf "$msg" $s)
    notify-send "Time's up!" "$txt" --icon=$icon --expire-time=200
    sleep 1.5
done

s=" =================================================================================================================================================================================== "

# STOP message
for i in $(seq 1 $nb_stop)
do
    notify-send "Time's up!" "${s}$end_msg${s}" \
        --icon=dialog-error --expire-time=20000
done

sleep $lock_delay
xflock4
